can_id_map_path = /home/zhuziyi/jobs/client-cpp-bench/data/canIdMap.txt
csv_data_path = /home/zhuziyi/jobs/client-cpp-bench/data/data.csv
insert_point_number = 2000000
max_insert_point_per_sec = 300000000
write_task_number = 1
write_buffer_size = 512
batch_number = 6000
write_http_endpoint = 127.0.0.1:4000
